### ISSUE TITLE
Dependency conflicts and errors

### ISSUE THREAD

**Issue by reemTamimi** [bklynhlth/openwillis#110]
I would like to use the WhisperX speech transcription for the purpose of speaker recognition (our audio files are interviews, and I would like to parse the interviewer from the interviewee), to then implement other features. However, I am encountering some dependency conflicts, and essentially not being able to run a basic command similar to what is on the github repository.
 
Once I follow all of the steps on your getting started page, I turn to install WhisperX from their linked repository. WhisperX seems to successfully install, however, it installs pyannote.audio-3.1.1, where openwillis requires pyannote.audio-3.0.0, ultimately giving me an error because of that.
 
Also, when I try to run my command, I get a compute type error. WhisperX alone allows for the definition of a compute type, so that it can be changed. I don’t see that option within OpenWillis.

**Comment by GeorgeEfstathiadis** [comment]
Hi Reem, could you provide some more details this issue so that I am able to reproduce it.

1. What kind of device/os are you running this on?
2. Can you provide a screenshot of the exact code that's causing this error plus the error message itself?

I think that will help us solve this issue for you faster! The dependency conflict shouldn't be the root of this error here, so it's probably something else.

**Comment by reemTamimi** [comment]
I am running this on a iMac desktop, running Sonoma 14.0. I have attached the starter code below. The harvard.wav file is taken from an open Kaggle dataset.
<img width="1211" alt="code" src="https://github.com/bklynhlth/openwillis/assets/85123818/b346beed-cc5e-491a-9bf4-d5f0d467cc74">
Below is the error I receive upon running the code
<img width="1029" alt="code_error" src="https://github.com/bklynhlth/openwillis/assets/85123818/3b38f51e-5920-472e-ac88-d8c08307fec4">
Below is the error I got when I tried installing WhisperX, based on their documentation, after I installed openwillis in a conda environment
<img width="1032" alt="dependency_error" src="https://github.com/bklynhlth/openwillis/assets/85123818/c4925a26-a791-4b3c-8248-29bdc2f7e032">

**Comment by GeorgeEfstathiadis** [comment]
The issue seems to be with your device's memory, since it is running in CPU. We are adding now the option to edit `compute_type` and `batch_size` for WhisperX transcription, so you can change either of them to run it on your device. Reducing either of the parameters should fix the issue, but sacrificing performance or computation speed respectively.
