### ISSUE TITLE
Installation guide on Intel chip for Mac

### ISSUE THREAD

**Issue by reemTamimi** [bklynhlth/openwillis#155]
Are the installation directions different for a Mac with an Intel chip? I have successfully installed it on a Mac with a silicon chip, but when I try on a Mac with an Intel chip, everything seems to successfully install, but when I try to run a sample code, I get a segmentation fault error in the entire script, which comes from when openwillis is called.

**Comment by GeorgeEfstathiadis** [comment]
Sorry this is taking longer than expected to debug, we're trying to replicate your error to see what might be causing it.

While we do that, which part of `openwillis` is causing you that issue? Is it happening when you import the package or when running a function from `openwillis`?

**Comment by reemTamimi** [comment]
When I import the package, it doesn't error out. I am testing the speech transcription with whisper and that is where it seems to throw that error.

**Comment by reemTamimi** [comment]
Is there an update on a solution for this?

**Comment by reemTamimi** [comment]
Thank you for the update!

**Comment by GeorgeEfstathiadis** [comment]
Okay I was able to replicate your issue, which probably stems from memory allocation limitations in your device related to `whisperx`.

The solution is simply reducing the quality of some of the parameters in the transcription model. So when running with the default parameters for `speech_transcription_whisper` I got the same error as you did. I had to reduce the batch size (from 16 to 1; this affects the speed of computation) and the compute type-precision (from int16 to int8; this will affect the quality of the transcription).

If you are using the default parameters you should try to do the same to see if it solves your error. If you are changing any other parameters such as the model, you should try changing to a smaller model. Unfortunately all of these steps will decrease the quality of the output due to hardware limitations, but they will allow you to run this transcription in your device.

Example code to run for your analysis:
```python
import openwillis as ow
json_response, transcript = ow.speech_transcription_whisper(filepath, compute_type='int8', batch_size=1, ...) # all other parameters previously defined
```

That being said, even these changes may not allow you to run transcription with WhisperX, because your device's specs may not allow it. To test that I would try this sample code to load the models that are used in this function and see if they load successfully:

```python
import whisperx

whisperx.load_model('tiny', 'cpu', compute_type='int8')
whisperx.load_align_model(language_code='en', device='cpu')
```

**Comment by GeorgeEfstathiadis** [comment]
Additionally, I'm not sure of the content of your audio files, but if you have 1-speaker audio files that you wish to transcribe you can also use [speech transcription with Vosk](https://github.com/bklynhlth/openwillis/wiki/Speech-Transcription-with-Vosk-v1.0) which is less computationally heavy.

**Comment by reemTamimi** [comment]
The audio files I am using have more than one speaker, which is why Vosk is my last option, if I were to have to manually cut out the audio. I tried your recommendations and whisperX alone is loading in fine, but when I run the snippet of code for the speech_transcription_whisper with compute_type set to 'int8', it seems to get stuck. It has been running for quite some time, but doesn't error out, it just stays on the same step.

**Comment by GeorgeEfstathiadis** [comment]
Could you send me the exact code snippet you are running? I want to verify you are using the lowest resource options.

If you are indeed using the lowest ones, it might just be the case that you cannot run `speech_transcription_whisper` locally, due to resource constraints. If your data allow it you could consider cloud computing, either in AWS (paid computing) or Google Collab (free computing). Let me know you want to discuss more on this, you can also send me an email.

**Comment by reemTamimi** [comment]
Sorry for the delay in responding, I don't always have access to the Intel Mac.

The code snippet I am running is transcript_json,transcript_text = ow.speech_transcription_whisper(filepath = wav, compute_type = 'int8', batch_size = 1, model = 'tiny', hf_token = 'hf_W0emDNuf...')

I have used Google Collab before, are there any constraints when using openwillis with it?

**Comment by GeorgeEfstathiadis** [comment]
I think Google Collab is the best option then. We haven't tested all functions of OpenWillis on collab notebooks, but I don't expect you to have any major issues and especially `speech_transcription_whisper` should work fine for you.

**Comment by reemTamimi** [comment]
That sounds good, I will test it out and keep you updated with any issues I run into. Thanks for your continued help!
